import { type RouteConfig, route, index } from '@react-router/dev/routes'

export default [
  index('routes/_index.tsx'),
  route('pdf-compressor', 'routes/pdf-compressor.tsx'),
  route('pdf-merger', 'routes/pdf-merger.tsx'),
  route('pdf-converter', 'routes/pdf-converter.tsx'),
  route('pdf-splitter', 'routes/pdf-splitter.tsx'),
  route('json-formatter', 'routes/json-formatter.tsx'),
  route('regex-tester', 'routes/regex-tester.tsx'),
  route('image-watermarker', 'routes/image-watermarker.tsx'),
  route('image-resizer', 'routes/image-resizer.tsx'),
  route('image-collage', 'routes/image-collage.tsx'),
  route('image-meme-generator', 'routes/image-meme-generator.tsx'),
  route('image-crop', 'routes/image-crop.tsx'),
  route('image-converter', 'routes/image-converter.tsx'),
  route('image-rotator', 'routes/image-rotator.tsx'),
  route('screen-recorder', 'routes/screen-recorder.tsx'),
  route('about/us', 'routes/about.us.tsx'),
  route('about/policy', 'routes/about.policy.tsx'),
  route('about/terms', 'routes/about.terms.tsx'),
  route('contact', 'routes/contact.tsx'),
  route('blogs', 'routes/blogs._index.tsx'),
  route('blogs/:slug', 'routes/blogs.$slug.tsx'),
  route('api/blogs', 'routes/api.blogs.tsx'),
  route('api/blogs/:slug', 'routes/api.blogs.$slug.tsx'),
  route('r2-presign', 'routes/r2-presign.ts'),
  route('api/r2-presign', 'routes/api.r2-presign.ts'),
] satisfies RouteConfig
