// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/pdf-compressor": {
    params: {};
  };
  "/pdf-merger": {
    params: {};
  };
  "/pdf-converter": {
    params: {};
  };
  "/pdf-splitter": {
    params: {};
  };
  "/json-formatter": {
    params: {};
  };
  "/regex-tester": {
    params: {};
  };
  "/image-watermarker": {
    params: {};
  };
  "/image-resizer": {
    params: {};
  };
  "/image-collage": {
    params: {};
  };
  "/image-meme-generator": {
    params: {};
  };
  "/image-crop": {
    params: {};
  };
  "/image-converter": {
    params: {};
  };
  "/image-rotator": {
    params: {};
  };
  "/screen-recorder": {
    params: {};
  };
  "/about/us": {
    params: {};
  };
  "/about/policy": {
    params: {};
  };
  "/about/terms": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/blogs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/api/blogs": {
    params: {};
  };
  "/api/blogs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/r2-presign": {
    params: {};
  };
  "/api/r2-presign": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/pdf-compressor" | "/pdf-merger" | "/pdf-converter" | "/pdf-splitter" | "/json-formatter" | "/regex-tester" | "/image-watermarker" | "/image-resizer" | "/image-collage" | "/image-meme-generator" | "/image-crop" | "/image-converter" | "/image-rotator" | "/screen-recorder" | "/about/us" | "/about/policy" | "/about/terms" | "/contact" | "/blogs" | "/blogs/:slug" | "/api/blogs" | "/api/blogs/:slug" | "/r2-presign" | "/api/r2-presign";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/pdf-compressor.tsx": {
    id: "routes/pdf-compressor";
    page: "/pdf-compressor";
  };
  "routes/pdf-merger.tsx": {
    id: "routes/pdf-merger";
    page: "/pdf-merger";
  };
  "routes/pdf-converter.tsx": {
    id: "routes/pdf-converter";
    page: "/pdf-converter";
  };
  "routes/pdf-splitter.tsx": {
    id: "routes/pdf-splitter";
    page: "/pdf-splitter";
  };
  "routes/json-formatter.tsx": {
    id: "routes/json-formatter";
    page: "/json-formatter";
  };
  "routes/regex-tester.tsx": {
    id: "routes/regex-tester";
    page: "/regex-tester";
  };
  "routes/image-watermarker.tsx": {
    id: "routes/image-watermarker";
    page: "/image-watermarker";
  };
  "routes/image-resizer.tsx": {
    id: "routes/image-resizer";
    page: "/image-resizer";
  };
  "routes/image-collage.tsx": {
    id: "routes/image-collage";
    page: "/image-collage";
  };
  "routes/image-meme-generator.tsx": {
    id: "routes/image-meme-generator";
    page: "/image-meme-generator";
  };
  "routes/image-crop.tsx": {
    id: "routes/image-crop";
    page: "/image-crop";
  };
  "routes/image-converter.tsx": {
    id: "routes/image-converter";
    page: "/image-converter";
  };
  "routes/image-rotator.tsx": {
    id: "routes/image-rotator";
    page: "/image-rotator";
  };
  "routes/screen-recorder.tsx": {
    id: "routes/screen-recorder";
    page: "/screen-recorder";
  };
  "routes/about.us.tsx": {
    id: "routes/about.us";
    page: "/about/us";
  };
  "routes/about.policy.tsx": {
    id: "routes/about.policy";
    page: "/about/policy";
  };
  "routes/about.terms.tsx": {
    id: "routes/about.terms";
    page: "/about/terms";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/blogs._index.tsx": {
    id: "routes/blogs._index";
    page: "/blogs";
  };
  "routes/blogs.$slug.tsx": {
    id: "routes/blogs.$slug";
    page: "/blogs/:slug";
  };
  "routes/api.blogs.tsx": {
    id: "routes/api.blogs";
    page: "/api/blogs";
  };
  "routes/api.blogs.$slug.tsx": {
    id: "routes/api.blogs.$slug";
    page: "/api/blogs/:slug";
  };
  "routes/r2-presign.ts": {
    id: "routes/r2-presign";
    page: "/r2-presign";
  };
  "routes/api.r2-presign.ts": {
    id: "routes/api.r2-presign";
    page: "/api/r2-presign";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/pdf-compressor": typeof import("./app/routes/pdf-compressor.tsx");
  "routes/pdf-merger": typeof import("./app/routes/pdf-merger.tsx");
  "routes/pdf-converter": typeof import("./app/routes/pdf-converter.tsx");
  "routes/pdf-splitter": typeof import("./app/routes/pdf-splitter.tsx");
  "routes/json-formatter": typeof import("./app/routes/json-formatter.tsx");
  "routes/regex-tester": typeof import("./app/routes/regex-tester.tsx");
  "routes/image-watermarker": typeof import("./app/routes/image-watermarker.tsx");
  "routes/image-resizer": typeof import("./app/routes/image-resizer.tsx");
  "routes/image-collage": typeof import("./app/routes/image-collage.tsx");
  "routes/image-meme-generator": typeof import("./app/routes/image-meme-generator.tsx");
  "routes/image-crop": typeof import("./app/routes/image-crop.tsx");
  "routes/image-converter": typeof import("./app/routes/image-converter.tsx");
  "routes/image-rotator": typeof import("./app/routes/image-rotator.tsx");
  "routes/screen-recorder": typeof import("./app/routes/screen-recorder.tsx");
  "routes/about.us": typeof import("./app/routes/about.us.tsx");
  "routes/about.policy": typeof import("./app/routes/about.policy.tsx");
  "routes/about.terms": typeof import("./app/routes/about.terms.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/blogs._index": typeof import("./app/routes/blogs._index.tsx");
  "routes/blogs.$slug": typeof import("./app/routes/blogs.$slug.tsx");
  "routes/api.blogs": typeof import("./app/routes/api.blogs.tsx");
  "routes/api.blogs.$slug": typeof import("./app/routes/api.blogs.$slug.tsx");
  "routes/r2-presign": typeof import("./app/routes/r2-presign.ts");
  "routes/api.r2-presign": typeof import("./app/routes/api.r2-presign.ts");
};